### ISSUE TITLE
I dont use two <div>

### ISSUE THREAD

**Issue by KarloxMartinez** [bachors/jQuery-Awesome-Sosmed-Share-Button#9]
that don not work counts then i use two divs

**Comment by bachors** [comment]
Great.. I'll change this selector using a class name :+1:

**Comment by KarloxMartinez** [comment]
neither

**Comment by bachors** [comment]
I have to fix it.
see this demo http://ibacor.com/download/demo/share-button/

**Comment by KarloxMartinez** [comment]
Thanks

**Comment by bachors** [comment]
your welcome :+1:
